use anyhow::{Context, Result};
use clap::Args;
use colored::Colorize;
use std::path::PathBuf;

use crate::config::{self, Template};

#[derive(Args, Debug)]
pub struct InitCiArgs {
    /// CPU count to allocate for the enclave.
    #[arg(long, default_value = "2")]
    pub cpu_count: u32,

    /// Memory in MiB to allocate for the enclave.
    #[arg(long, default_value = "4096")]
    pub memory_mib: u32,

    /// Path to the Dockerfile used in the CI build step.
    #[arg(short = 'f', long, default_value = "Dockerfile")]
    pub dockerfile: PathBuf,

    /// Output directory for the generated workflow file.
    #[arg(long, default_value = ".github/workflows")]
    pub output_dir: PathBuf,
}

pub async fn run(mut args: InitCiArgs, cli_template: Option<Template>) -> Result<()> {
    let cfg = config::NautilusConfig::load(None).unwrap_or_default();
    let template = config::resolve_template(cli_template, &cfg)?;

    // Auto-detect Containerfile if default Dockerfile doesn't exist
    if args.dockerfile == PathBuf::from("Dockerfile") && !args.dockerfile.exists() {
        if PathBuf::from("Containerfile").exists() {
            args.dockerfile = PathBuf::from("Containerfile");
        }
    }

    println!("{}", "Nautilus CI/CD Scaffold".bold().cyan());
    println!(
        "{} Template: {}",
        "→".cyan(),
        template.to_string().cyan().bold()
    );
    println!("{}", "─".repeat(40).dimmed());

    let workflow = match template {
        Template::Rust => generate_workflow_rust(&args),
        Template::Ts => generate_workflow_ts(&args),
        Template::Python => generate_workflow_python(&args),
    };
    let workflow_path = args.output_dir.join("nautilus-deploy.yml");

    std::fs::create_dir_all(&args.output_dir)
        .context("Failed to create .github/workflows directory")?;
    std::fs::write(&workflow_path, &workflow)
        .with_context(|| format!("Failed to write workflow to {}", workflow_path.display()))?;

    println!(
        "{} Generated: {}",
        "✔".green().bold(),
        workflow_path.display()
    );
    println!();
    println!("{}", "➜  Required GitHub Secrets".bold().yellow());
    println!("   Add these via: Settings → Secrets and Variables → Actions\n");

    let secrets = [
        ("TEE_EC2_HOST",    "Public IP or DNS of your Nitro-enabled EC2 instance"),
        ("TEE_EC2_USER",    "SSH username (e.g. ec2-user)"),
        ("TEE_EC2_SSH_KEY", "Private SSH key (-----BEGIN RSA PRIVATE KEY-----)"),
    ];

    for (name, desc) in &secrets {
        println!(
            "   {} {:<20}  {}",
            "▶".dimmed(),
            name.cyan().bold(),
            desc.dimmed()
        );
    }

    println!();
    println!(
        "{} Push to {} to trigger your first deployment.",
        "ℹ".bold().blue(),
        "main".bold()
    );

    Ok(())
}

fn ssh_preamble() -> &'static str {
    r#"          echo "$EC2_KEY" > /tmp/deploy_key && chmod 600 /tmp/deploy_key
          SSH_OPTS="-o StrictHostKeyChecking=no -o ServerAliveInterval=30 -o ServerAliveCountMax=10"
          ssh $SSH_OPTS -i /tmp/deploy_key "$EC2_USER@$EC2_HOST" 'bash -s' << 'REMOTE'"#
}

fn ssh_env() -> &'static str {
    r#"        env:
          EC2_HOST: ${{ secrets.TEE_EC2_HOST }}
          EC2_USER: ${{ secrets.TEE_EC2_USER }}
          EC2_KEY: ${{ secrets.TEE_EC2_SSH_KEY }}"#
}

fn generate_workflow_rust(args: &InitCiArgs) -> String {
    let dockerfile = args.dockerfile.display();
    let cpu = args.cpu_count;
    let mem = args.memory_mib;
    let env = ssh_env();
    let preamble = ssh_preamble();

    format!(
        r#"# Generated by nautilus-cli init-ci (template: rust)
name: Deploy Enclave

on:
  push:
    branches: [main]

concurrency:
  group: deploy-enclave
  cancel-in-progress: true

env:
  APP_DIR: nautilus-app
  ENCLAVE_CPU: {cpu}
  ENCLAVE_MEM: {mem}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy source to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{{{ secrets.TEE_EC2_HOST }}}}
          username: ${{{{ secrets.TEE_EC2_USER }}}}
          key: ${{{{ secrets.TEE_EC2_SSH_KEY }}}}
          source: "Containerfile,src,Cargo.toml,Cargo.lock,Makefile,.gitignore"
          target: "~/nautilus-app/"
          overwrite: true
          rm: false

      - name: Install dependencies
{env}
        run: |
{preamble}
          set -e
          # Detect package manager (AL2023 uses dnf, AL2 uses yum/amazon-linux-extras)
          if command -v dnf &> /dev/null; then
            PKG="sudo dnf"
          else
            PKG="sudo yum"
          fi

          if ! command -v docker &> /dev/null; then
            $PKG install -y docker || (curl -fsSL https://get.docker.com | sudo sh)
            sudo systemctl start docker && sudo systemctl enable docker
            sudo usermod -aG docker $USER
          fi
          if ! command -v nitro-cli &> /dev/null; then
            $PKG install -y aws-nitro-enclaves-cli aws-nitro-enclaves-cli-devel
            sudo usermod -aG ne $USER
          fi
          command -v socat &> /dev/null || $PKG install -y socat
          command -v jq    &> /dev/null || $PKG install -y jq
          echo "Dependencies ready"
          REMOTE
          rm -f /tmp/deploy_key

      - name: Configure enclave allocator
{env}
        run: |
{preamble}
          set -e
          ALLOC=/etc/nitro_enclaves/allocator.yaml
          sudo sed -i "s/memory_mib:.*/memory_mib: {mem}/" "$ALLOC" || true
          sudo sed -i "s/cpu_count:.*/cpu_count: {cpu}/"   "$ALLOC" || true
          sudo systemctl restart nitro-enclaves-allocator.service || true
          sudo systemctl enable  nitro-enclaves-allocator.service || true
          REMOTE
          rm -f /tmp/deploy_key

      - name: Build enclave image
{env}
        run: |
{preamble}
          set -e
          cd ~/nautilus-app && rm -rf out && mkdir -p out
          sudo docker build \
            --platform linux/amd64 \
            --progress=plain \
            --output type=local,dest=out/ \
            -f {dockerfile} . 2>&1 | tee out/docker.log
          echo "--- PCR Measurements ---"
          cat out/nitro.pcrs || true
          REMOTE
          rm -f /tmp/deploy_key

      - name: Terminate old enclave
{env}
        run: |
{preamble}
          sudo pkill -f "socat.*4000" 2>/dev/null || true
          sudo pkill -f "socat.*5000" 2>/dev/null || true
          sudo systemctl stop nautilus-bridge.service 2>/dev/null || true
          sudo systemctl stop nautilus-logs.service   2>/dev/null || true
          sudo nitro-cli terminate-enclave --all      || true
          REMOTE
          rm -f /tmp/deploy_key

      - name: Launch enclave
{env}
        run: |
{preamble}
          set -e
          sudo nitro-cli run-enclave \
            --cpu-count {cpu} \
            --memory {mem} \
            --eif-path ~/nautilus-app/out/nitro.eif
          sudo nitro-cli describe-enclaves | jq -r '.[0] | "CID: \(.EnclaveCID)  State: \(.State)"'
          REMOTE
          rm -f /tmp/deploy_key

      - name: Setup VSOCK bridge
{env}
        run: |
{preamble}
          set -e
          # Wait for enclave CID to become available
          for i in 1 2 3 4 5; do
            CID=$(sudo nitro-cli describe-enclaves | jq -r '.[0].EnclaveCID // empty')
            [ -n "$CID" ] && break
            echo "Waiting for enclave CID... (attempt $i)"
            sleep 2
          done
          if [ -z "$CID" ]; then
            echo "ERROR: Could not get enclave CID"
            sudo nitro-cli describe-enclaves
            exit 1
          fi

          # Kill any stale socat processes
          sudo pkill -f "socat.*4000" 2>/dev/null || true
          sudo pkill -f "socat.*5000" 2>/dev/null || true

          sudo tee /etc/systemd/system/nautilus-bridge.service > /dev/null <<EOF
          [Unit]
          Description=Nautilus VSOCK Bridge (TCP:4000 <-> VSOCK:4000)
          After=network.target

          [Service]
          ExecStart=/usr/bin/socat TCP-LISTEN:4000,reuseaddr,fork VSOCK-CONNECT:$CID:4000
          Restart=always
          RestartSec=2

          [Install]
          WantedBy=multi-user.target
          EOF

          sudo tee /etc/systemd/system/nautilus-logs.service > /dev/null <<EOF
          [Unit]
          Description=Nautilus Log Collector (VSOCK:5000)
          After=network.target

          [Service]
          ExecStart=/usr/bin/socat VSOCK-LISTEN:5000,fork,reuseaddr OPEN:/tmp/enclave.log,creat,append
          Restart=always
          RestartSec=2

          [Install]
          WantedBy=multi-user.target
          EOF

          sudo systemctl daemon-reload
          sudo systemctl enable --now nautilus-bridge.service nautilus-logs.service
          sleep 2
          sudo systemctl is-active nautilus-bridge.service
          echo "Bridge active: CID=$CID  TCP:4000 -> VSOCK:4000"
          REMOTE
          rm -f /tmp/deploy_key
"#,
        dockerfile = dockerfile,
        cpu = cpu,
        mem = mem,
        env = env,
        preamble = preamble,
    )
}

fn generate_workflow_ts(args: &InitCiArgs) -> String {
    let cpu = args.cpu_count;
    let mem = args.memory_mib;
    let env = ssh_env();
    let preamble = ssh_preamble();

    format!(
        r#"# Generated by nautilus-cli init-ci (template: ts)
name: Deploy Enclave (TypeScript)

on:
  push:
    branches: [main]

concurrency:
  group: deploy-enclave
  cancel-in-progress: true

env:
  APP_DIR: nautilus-app
  ENCLAVE_CPU: {cpu}
  ENCLAVE_MEM: {mem}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy source to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{{{ secrets.TEE_EC2_HOST }}}}
          username: ${{{{ secrets.TEE_EC2_USER }}}}
          key: ${{{{ secrets.TEE_EC2_SSH_KEY }}}}
          source: "Containerfile,src,argonaut,package.json,bun.lock,tsconfig.json,Makefile"
          target: "~/nautilus-app/"
          overwrite: true
          rm: false

      - name: Install dependencies
{env}
        run: |
{preamble}
          set -e
          # Detect package manager (AL2023 uses dnf, AL2 uses yum/amazon-linux-extras)
          if command -v dnf &> /dev/null; then
            PKG="sudo dnf"
          else
            PKG="sudo yum"
          fi

          if ! command -v docker &> /dev/null; then
            $PKG install -y docker || (curl -fsSL https://get.docker.com | sudo sh)
            sudo systemctl start docker && sudo systemctl enable docker
            sudo usermod -aG docker $USER
          fi
          if ! command -v nitro-cli &> /dev/null; then
            $PKG install -y aws-nitro-enclaves-cli aws-nitro-enclaves-cli-devel
            sudo usermod -aG ne $USER
          fi
          command -v jq   &> /dev/null || $PKG install -y jq
          command -v make &> /dev/null || $PKG install -y make
          echo "Dependencies ready"
          REMOTE
          rm -f /tmp/deploy_key

      - name: Configure enclave allocator
{env}
        run: |
{preamble}
          set -e
          ALLOC=/etc/nitro_enclaves/allocator.yaml
          sudo sed -i "s/memory_mib:.*/memory_mib: {mem}/" "$ALLOC" || true
          sudo sed -i "s/cpu_count:.*/cpu_count: {cpu}/"   "$ALLOC" || true
          sudo systemctl restart nitro-enclaves-allocator.service || true
          sudo systemctl enable  nitro-enclaves-allocator.service || true
          REMOTE
          rm -f /tmp/deploy_key

      - name: Build enclave image
{env}
        run: |
{preamble}
          set -e
          cd ~/nautilus-app && rm -rf out && mkdir -p out
          sudo make 2>&1 | tee out/build.log
          echo "--- PCR Measurements ---"
          cat out/nitro.pcrs || true
          REMOTE
          rm -f /tmp/deploy_key

      - name: Terminate old enclave
{env}
        run: |
{preamble}
          sudo systemctl stop nautilus-argonaut.service 2>/dev/null || true
          sudo pkill -f "argonaut host" 2>/dev/null || true
          sudo nitro-cli terminate-enclave --all || true
          REMOTE
          rm -f /tmp/deploy_key

      - name: Launch enclave
{env}
        run: |
{preamble}
          set -e
          sudo nitro-cli run-enclave \
            --cpu-count {cpu} \
            --memory {mem} \
            --eif-path ~/nautilus-app/out/nitro.eif
          sudo nitro-cli describe-enclaves | jq -r '.[0] | "CID: \(.EnclaveCID)  State: \(.State)"'
          REMOTE
          rm -f /tmp/deploy_key

      - name: Write boot config
{env}
        run: |
{preamble}
          cat > ~/nautilus-app/config.json <<'EOF'
          {{
            "httpPort": 3000,
            "httpVsockPort": 3000,
            "endpoints": [],
            "logLevel": "info"
          }}
          EOF
          REMOTE
          rm -f /tmp/deploy_key

      - name: Setup argonaut bridge
{env}
        run: |
{preamble}
          set -e
          CID=$(sudo nitro-cli describe-enclaves | jq -r '.[0].EnclaveCID')

          sudo tee /etc/systemd/system/nautilus-argonaut.service > /dev/null <<EOF
          [Unit]
          Description=Nautilus Argonaut Bridge (port 3000)
          After=network.target

          [Service]
          ExecStart=$HOME/nautilus-app/out/argonaut host $CID $HOME/nautilus-app/config.json
          Restart=always
          RestartSec=2

          [Install]
          WantedBy=multi-user.target
          EOF

          sudo systemctl daemon-reload
          sudo systemctl enable --now nautilus-argonaut.service
          sleep 3
          if ! sudo systemctl is-active nautilus-argonaut.service; then
            echo "--- argonaut service failed, showing logs ---"
            sudo journalctl -u nautilus-argonaut.service --no-pager -n 30
            cat /etc/systemd/system/nautilus-argonaut.service
            ls -la $HOME/nautilus-app/out/argonaut || true
            exit 1
          fi
          echo "Argonaut bridge active: CID=$CID  port=3000"
          REMOTE
          rm -f /tmp/deploy_key
"#,
        cpu = cpu,
        mem = mem,
        env = env,
        preamble = preamble,
    )
}

fn generate_workflow_python(args: &InitCiArgs) -> String {
    let cpu = args.cpu_count;
    let mem = args.memory_mib;
    let env = ssh_env();
    let preamble = ssh_preamble();

    format!(
        r#"# Generated by nautilus-cli init-ci (template: python)
name: Deploy Enclave (Python)

on:
  push:
    branches: [main]

concurrency:
  group: deploy-enclave
  cancel-in-progress: true

env:
  APP_DIR: nautilus-app
  ENCLAVE_CPU: {cpu}
  ENCLAVE_MEM: {mem}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Copy source to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{{{ secrets.TEE_EC2_HOST }}}}
          username: ${{{{ secrets.TEE_EC2_USER }}}}
          key: ${{{{ secrets.TEE_EC2_SSH_KEY }}}}
          source: "Containerfile,app.py,src,requirements.txt,Makefile"
          target: "~/nautilus-app/"
          overwrite: true
          rm: false

      - name: Install dependencies
{env}
        run: |
{preamble}
          set -e
          # Detect package manager (AL2023 uses dnf, AL2 uses yum/amazon-linux-extras)
          if command -v dnf &> /dev/null; then
            PKG="sudo dnf"
          else
            PKG="sudo yum"
          fi

          if ! command -v docker &> /dev/null; then
            $PKG install -y docker || (curl -fsSL https://get.docker.com | sudo sh)
            sudo systemctl start docker && sudo systemctl enable docker
            sudo usermod -aG docker $USER
          fi
          if ! command -v nitro-cli &> /dev/null; then
            $PKG install -y aws-nitro-enclaves-cli aws-nitro-enclaves-cli-devel
            sudo usermod -aG ne $USER
          fi
          command -v socat &> /dev/null || $PKG install -y socat
          command -v jq    &> /dev/null || $PKG install -y jq
          command -v make  &> /dev/null || $PKG install -y make
          echo "Dependencies ready"
          REMOTE
          rm -f /tmp/deploy_key

      - name: Configure enclave allocator
{env}
        run: |
{preamble}
          set -e
          ALLOC=/etc/nitro_enclaves/allocator.yaml
          sudo sed -i "s/memory_mib:.*/memory_mib: {mem}/" "$ALLOC" || true
          sudo sed -i "s/cpu_count:.*/cpu_count: {cpu}/"   "$ALLOC" || true
          sudo systemctl restart nitro-enclaves-allocator.service || true
          sudo systemctl enable  nitro-enclaves-allocator.service || true
          REMOTE
          rm -f /tmp/deploy_key

      - name: Build enclave image
{env}
        run: |
{preamble}
          set -e
          cd ~/nautilus-app && rm -rf out && mkdir -p out
          sudo make 2>&1 | tee out/build.log
          echo "--- PCR Measurements ---"
          cat out/nitro.pcrs || true
          REMOTE
          rm -f /tmp/deploy_key

      - name: Launch enclave and setup bridge
{env}
        run: |
{preamble}
          set -e

          # Terminate old enclave and stale processes
          sudo pkill -f "socat.*5000" 2>/dev/null || true
          sudo systemctl stop nautilus-bridge.service 2>/dev/null || true
          sudo systemctl stop nautilus-logs.service   2>/dev/null || true
          sudo nitro-cli terminate-enclave --all      || true
          sleep 2

          # Re-reserve CPUs after Docker build may have disrupted the pool
          sudo systemctl restart nitro-enclaves-allocator.service
          sleep 2

          # Launch enclave
          sudo nitro-cli run-enclave \
            --cpu-count {cpu} \
            --memory {mem} \
            --eif-path ~/nautilus-app/out/nitro.eif
          sleep 3

          # Get CID (retry up to 5 times)
          for i in 1 2 3 4 5; do
            CID=$(sudo nitro-cli describe-enclaves | jq -r '.[0].EnclaveCID // empty')
            STATE=$(sudo nitro-cli describe-enclaves | jq -r '.[0].State // empty')
            echo "Attempt $i: CID=$CID State=$STATE"
            [ -n "$CID" ] && break
            echo "Waiting for enclave CID... (attempt $i)"
            sleep 2
          done

          if [ -z "$CID" ]; then
            echo "ERROR: Enclave crashed. Checking dmesg for details:"
            sudo dmesg | tail -30
            exit 1
          fi

          # Kill any stale socat processes
          sudo pkill -f "socat.*5000" 2>/dev/null || true

          # Bridge wrapper resolves CID dynamically on each (re)start
          sudo tee /usr/local/bin/nautilus-bridge.sh > /dev/null <<'BRIDGEOF'
          #!/bin/bash
          CID=$(nitro-cli describe-enclaves | jq -r '.[0].EnclaveCID // empty')
          if [ -z "$CID" ]; then echo "No enclave running"; exit 1; fi
          echo "Bridging TCP:5000 <-> VSOCK:$CID:5000"
          exec /usr/bin/socat TCP-LISTEN:5000,reuseaddr,fork VSOCK-CONNECT:$CID:5000
          BRIDGEOF
          sudo chmod +x /usr/local/bin/nautilus-bridge.sh

          # Setup bridge service (TCP:5000 <-> VSOCK:5000)
          sudo tee /etc/systemd/system/nautilus-bridge.service > /dev/null <<EOF
          [Unit]
          Description=Nautilus VSOCK Bridge (TCP:5000 <-> VSOCK:5000)
          After=network.target

          [Service]
          ExecStart=/usr/local/bin/nautilus-bridge.sh
          Restart=always
          RestartSec=2

          [Install]
          WantedBy=multi-user.target
          EOF

          # Setup log collector service
          sudo tee /etc/systemd/system/nautilus-logs.service > /dev/null <<EOF
          [Unit]
          Description=Nautilus Log Collector (VSOCK:5001)
          After=network.target

          [Service]
          ExecStart=/usr/bin/socat VSOCK-LISTEN:5001,fork,reuseaddr OPEN:/tmp/enclave.log,creat,append
          Restart=always
          RestartSec=2

          [Install]
          WantedBy=multi-user.target
          EOF

          sudo systemctl daemon-reload
          sudo systemctl enable --now nautilus-bridge.service nautilus-logs.service
          sleep 2
          sudo systemctl is-active nautilus-bridge.service
          echo "Bridge active: CID=$CID  TCP:5000 -> VSOCK:5000"
          REMOTE
          rm -f /tmp/deploy_key
"#,
        cpu = cpu,
        mem = mem,
        env = env,
        preamble = preamble,
    )
}

// ─────────────────────────────────────────────
// Unit Tests
// ─────────────────────────────────────────────
#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn default_args(tmp: &TempDir) -> InitCiArgs {
        InitCiArgs {
            cpu_count: 2,
            memory_mib: 4096,
            dockerfile: PathBuf::from("Dockerfile"),
            output_dir: tmp.path().join(".github/workflows"),
        }
    }

    #[test]
    fn test_generate_rust_workflow_contains_required_secrets() {
        let args = default_args(&TempDir::new().unwrap());
        let content = generate_workflow_rust(&args);
        assert!(content.contains("TEE_EC2_HOST"));
        assert!(content.contains("TEE_EC2_USER"));
        assert!(content.contains("TEE_EC2_SSH_KEY"));
        assert!(content.contains("nitro-cli run-enclave"));
        assert!(content.contains("appleboy/scp-action"));
        assert!(content.contains("socat"));
    }

    #[test]
    fn test_generate_rust_workflow_uses_correct_resources() {
        let args = InitCiArgs {
            cpu_count: 4,
            memory_mib: 8192,
            dockerfile: PathBuf::from("Containerfile"),
            output_dir: PathBuf::from(".github/workflows"),
        };
        let content = generate_workflow_rust(&args);
        assert!(content.contains("--cpu-count 4"));
        assert!(content.contains("--memory 8192"));
        assert!(content.contains("Containerfile"));
    }

    #[test]
    fn test_generate_rust_workflow_is_valid_yaml_shape() {
        let args = default_args(&TempDir::new().unwrap());
        let yaml = generate_workflow_rust(&args);
        assert!(yaml.trim_start().starts_with('#') || yaml.trim_start().starts_with("name:"));
        assert!(yaml.contains("on:"));
        assert!(yaml.contains("jobs:"));
    }

    #[test]
    fn test_generate_ts_workflow_uses_argonaut() {
        let args = default_args(&TempDir::new().unwrap());
        let content = generate_workflow_ts(&args);
        assert!(content.contains("argonaut"));
        assert!(content.contains("make"));
        assert!(content.contains("nautilus-argonaut.service"));
        assert!(!content.contains("socat"));
    }

    #[test]
    fn test_generate_ts_workflow_copies_correct_sources() {
        let args = default_args(&TempDir::new().unwrap());
        let content = generate_workflow_ts(&args);
        assert!(content.contains("package.json"));
        assert!(content.contains("bun.lock"));
        assert!(content.contains("tsconfig.json"));
    }

    #[test]
    fn test_generate_ts_workflow_is_valid_yaml_shape() {
        let args = default_args(&TempDir::new().unwrap());
        let yaml = generate_workflow_ts(&args);
        assert!(yaml.trim_start().starts_with('#') || yaml.trim_start().starts_with("name:"));
        assert!(yaml.contains("on:"));
        assert!(yaml.contains("jobs:"));
    }

    #[test]
    fn test_generate_python_workflow_uses_socat() {
        let args = default_args(&TempDir::new().unwrap());
        let content = generate_workflow_python(&args);
        assert!(content.contains("socat"));
        assert!(content.contains("5000"));
        assert!(content.contains("requirements.txt"));
        assert!(content.contains("app.py"));
    }

    #[test]
    fn test_generate_python_workflow_is_valid_yaml_shape() {
        let args = default_args(&TempDir::new().unwrap());
        let yaml = generate_workflow_python(&args);
        assert!(yaml.trim_start().starts_with('#') || yaml.trim_start().starts_with("name:"));
        assert!(yaml.contains("on:"));
        assert!(yaml.contains("jobs:"));
    }
}
