use anyhow::{Context, Result};
use clap::Args;
use colored::Colorize;
use std::path::PathBuf;

#[derive(Args, Debug)]
pub struct InitCiArgs {
    /// CPU count to allocate for the enclave.
    #[arg(long, default_value = "2")]
    pub cpu_count: u32,

    /// Memory in MiB to allocate for the enclave.
    #[arg(long, default_value = "4096")]
    pub memory_mib: u32,

    /// Path to the Dockerfile used in the CI build step.
    #[arg(short = 'f', long, default_value = "Dockerfile")]
    pub dockerfile: PathBuf,

    /// Output directory for the generated workflow file.
    #[arg(long, default_value = ".github/workflows")]
    pub output_dir: PathBuf,
}

pub async fn run(args: InitCiArgs) -> Result<()> {
    println!("{}", "Nautilus CI/CD Scaffold".bold().cyan());
    println!("{}", "─".repeat(40).dimmed());

    let workflow = generate_workflow(&args);
    let workflow_path = args.output_dir.join("nautilus-deploy.yml");

    std::fs::create_dir_all(&args.output_dir)
        .context("Failed to create .github/workflows directory")?;
    std::fs::write(&workflow_path, &workflow)
        .with_context(|| format!("Failed to write workflow to {}", workflow_path.display()))?;

    println!(
        "{} Generated: {}",
        "✔".green().bold(),
        workflow_path.display()
    );
    println!();
    println!("{}", "➜  Required GitHub Secrets".bold().yellow());
    println!("   Add these via: Settings → Secrets and Variables → Actions\n");

    let secrets = [
        ("TEE_EC2_HOST",    "Public IP or DNS of your Nitro-enabled EC2 instance"),
        ("TEE_EC2_USER",    "SSH username (e.g. ec2-user)"),
        ("TEE_EC2_SSH_KEY", "Private SSH key (-----BEGIN RSA PRIVATE KEY-----)"),
    ];

    for (name, desc) in &secrets {
        println!(
            "   {} {:<20}  {}",
            "▶".dimmed(),
            name.cyan().bold(),
            desc.dimmed()
        );
    }

    println!();
    println!(
        "{} Push to {} to trigger your first deployment.",
        "ℹ".bold().blue(),
        "main".bold()
    );

    Ok(())
}

fn generate_workflow(args: &InitCiArgs) -> String {
    let dockerfile = args.dockerfile.display();
    let cpu = args.cpu_count;
    let mem = args.memory_mib;

    format!(
        r#"# Generated by nautilus-cli init-ci
# Strategy: push source to EC2, build EIF there, run enclave.
# EC2 setup (Docker, nitro-cli) is handled automatically on first run.
name: Deploy Enclave

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ── Copy source to EC2 ───────────────────────────────────────────
      - name: Copy source to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{{{ secrets.TEE_EC2_HOST }}}}
          username: ${{{{ secrets.TEE_EC2_USER }}}}
          key: ${{{{ secrets.TEE_EC2_SSH_KEY }}}}
          source: "."
          target: "~/nautilus-app/"
          overwrite: true

      # ── Setup EC2 + build + deploy (all on EC2) ──────────────────────
      - name: Setup, Build and Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{{{ secrets.TEE_EC2_HOST }}}}
          username: ${{{{ secrets.TEE_EC2_USER }}}}
          key: ${{{{ secrets.TEE_EC2_SSH_KEY }}}}
          command_timeout: 30m
          script: |
            set -e

            # ── Install Docker if missing ─────────────────────────────
            if ! command -v docker &> /dev/null; then
              echo "=== Installing Docker ==="
              sudo yum update -y
              sudo amazon-linux-extras install docker -y || \
                (curl -fsSL https://get.docker.com | sudo sh)
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker $USER
              echo "Docker installed."
            else
              echo "Docker already installed: $(docker --version)"
            fi

            # ── Install nitro-cli if missing ──────────────────────────
            if ! command -v nitro-cli &> /dev/null; then
              echo "=== Installing nitro-cli ==="
              sudo amazon-linux-extras install aws-nitro-enclaves-cli -y
              sudo yum install -y aws-nitro-enclaves-cli-devel
              sudo usermod -aG ne $USER
              echo "nitro-cli installed."
            else
              echo "nitro-cli already installed: $(nitro-cli --version)"
            fi

            # ── Configure enclave allocator if not already set ────────
            ALLOC=/etc/nitro_enclaves/allocator.yaml
            if ! grep -q "memory_mib: {mem}" "$ALLOC" 2>/dev/null; then
              echo "=== Configuring enclave allocator ==="
              sudo sed -i "s/memory_mib:.*/memory_mib: {mem}/" "$ALLOC" || true
              sudo sed -i "s/cpu_count:.*/cpu_count: {cpu}/" "$ALLOC" || true
              sudo systemctl restart nitro-enclaves-allocator.service || true
              sudo systemctl enable nitro-enclaves-allocator.service || true
            fi

            # ── Install socat + jq if missing ─────────────────────────
            command -v socat &> /dev/null || sudo yum install -y socat
            command -v jq    &> /dev/null || sudo yum install -y jq

            # ── Build the EIF on EC2 ──────────────────────────────────
            echo "=== Building Enclave Image ==="
            cd ~/nautilus-app
            mkdir -p out

            # Run docker with sg ne group context
            sudo docker build \
              --tag local/enclaveos:{sha} \
              --platform linux/amd64 \
              --progress=plain \
              -f {dockerfile} \
              . 2>&1 | tee out/docker.log

            sudo nitro-cli build-enclave \
              --docker-uri local/enclaveos:{sha} \
              --output-file out/nautilus.eif \
              2>&1 | tee out/build.log

            # Extract PCRs
            grep '^{{' out/build.log | tail -1 > out/nautilus.pcrs.json || true
            echo "=== PCR Measurements ==="
            cat out/nautilus.pcrs.json || true

            # ── Terminate old enclave and start new one ───────────────
            echo "=== Terminating existing enclaves ==="
            sudo nitro-cli terminate-enclave --all || true

            echo "=== Starting new enclave ==="
            sudo nitro-cli run-enclave \
              --cpu-count {cpu} \
              --memory {mem} \
              --eif-path ~/nautilus-app/out/nautilus.eif

            echo "=== Running enclaves ==="
            sudo nitro-cli describe-enclaves

            # ── Start VSOCK bridge (restart if already running) ───────
            echo "=== Starting VSOCK bridge ==="
            pkill -f "socat.*VSOCK" || true
            sleep 1
            ENCLAVE_CID=$(sudo nitro-cli describe-enclaves | jq -r '.[0].EnclaveCID')
            nohup socat TCP-LISTEN:4000,reuseaddr,fork VSOCK-CONNECT:${{ENCLAVE_CID}}:4000 \
              > /tmp/vsock-bridge.log 2>&1 &
            nohup socat VSOCK-LISTEN:5000,reuseaddr,fork \
              OPEN:/tmp/enclave.log,creat,append \
              > /dev/null 2>&1 &

            echo ""
            echo "✔ Deployment complete."
            echo "  Enclave CID: ${{ENCLAVE_CID}}"
            echo "  Test: curl http://$(curl -s ifconfig.me):4000/health"
            echo "  Sign: curl -X POST http://$(curl -s ifconfig.me):4000/sign_name -H 'Content-Type: application/json' -d '{{\"name\":\"Ashwin\"}}'"
"#,
        dockerfile = dockerfile,
        cpu = cpu,
        mem = mem,
        sha = "${{ github.sha }}",
    )
}

// ─────────────────────────────────────────────
// Unit Tests
// ─────────────────────────────────────────────
#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn default_args(tmp: &TempDir) -> InitCiArgs {
        InitCiArgs {
            cpu_count: 2,
            memory_mib: 4096,
            dockerfile: PathBuf::from("Dockerfile"),
            output_dir: tmp.path().join(".github/workflows"),
        }
    }

    #[tokio::test]
    async fn test_init_ci_creates_file() {
        let tmp = TempDir::new().unwrap();
        let args = default_args(&tmp);
        let out_dir = args.output_dir.clone();

        run(args).await.expect("init-ci should succeed");

        let workflow = out_dir.join("nautilus-deploy.yml");
        assert!(workflow.exists(), "Expected workflow file to be created");
    }

    #[tokio::test]
    async fn test_generated_workflow_contains_required_secrets() {
        let tmp = TempDir::new().unwrap();
        let args = default_args(&tmp);
        let out_dir = args.output_dir.clone();

        run(args).await.unwrap();

        let content = std::fs::read_to_string(out_dir.join("nautilus-deploy.yml")).unwrap();
        assert!(content.contains("TEE_EC2_HOST"));
        assert!(content.contains("TEE_EC2_USER"));
        assert!(content.contains("TEE_EC2_SSH_KEY"));
        assert!(content.contains("nitro-cli run-enclave"));
        assert!(content.contains("appleboy/scp-action"));
    }

    #[tokio::test]
    async fn test_generated_workflow_uses_correct_resources() {
        let tmp = TempDir::new().unwrap();
        let args = InitCiArgs {
            cpu_count: 4,
            memory_mib: 8192,
            dockerfile: PathBuf::from("Containerfile"),
            output_dir: tmp.path().join(".github/workflows"),
        };
        let out_dir = args.output_dir.clone();

        run(args).await.unwrap();
        let content = std::fs::read_to_string(out_dir.join("nautilus-deploy.yml")).unwrap();

        assert!(content.contains("--cpu-count 4"));
        assert!(content.contains("--memory 8192"));
        assert!(content.contains("Containerfile"));
    }

    #[test]
    fn test_generate_workflow_is_valid_yaml_shape() {
        let args = InitCiArgs {
            cpu_count: 2,
            memory_mib: 4096,
            dockerfile: PathBuf::from("Dockerfile"),
            output_dir: PathBuf::from(".github/workflows"),
        };
        let yaml = generate_workflow(&args);
        // Basic sanity: YAML must start with a comment or key
        assert!(yaml.trim_start().starts_with('#') || yaml.trim_start().starts_with("name:"));
        assert!(yaml.contains("on:"));
        assert!(yaml.contains("jobs:"));
    }
}
